# Generated by Django 5.0.6 on 2024-06-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
